name: "Danger"

on:
  pull_request:
    branches:
      - "**"

jobs:
  danger:
    name: Danger JS
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3

      - name: Setup Node
        uses: actions/setup-node@2fddd8803e2f5c9604345a0b591c3020ee971a93 # tag=v3
        with:
          node-version: "16"
          cache: "yarn"
          cache-dependency-path: "website/yarn.lock"

      - name: Install Yarn Dependencies
        working-directory: bots/
        run: yarn install

      - name: Run Danger
        working-directory: bots/
        run: yarn danger ci
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
