name: "Danger"

on:
  pull_request:
    branches:
      - '**'

jobs:
  build:
    name: Danger JS
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Danger
        uses: danger/danger-js@10.1.1

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
